server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.instance_id:${random.value}}

spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER:localhost}:3306/${DB_NAME:db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:user}
    password: ${DB_PASSWD:pass}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true